### ISSUE TITLE
Problems about exgfeatures

### ISSUE THREAD

**Issue by Miracle-qi** [ucdrascal/axopy#35]
I want to run example.py, but I can't find the exgfeatures module.

**Comment by Miracle-qi** [comment]
@ixjlyons

**Comment by ixjlyons** [comment]
Sorry about that, AxoPy has changed a bit since the example was written and exgfeatures was a separate repo that I've decided to absorb into AxoPy instead. The example should be working again as of 9046ec2f06abeff0c4a969f1730bb1c3a25c4807. I'm hoping to produce more comprehensive examples and improved documentation soon, but you'll have to be a bit patient. AxoPy hasn't really officially been *released* yet, so it will go through some changes as I use it for my own work. Feel free to provide input or ask questions about the design and/or implementation if you're interested in helping out.

Closing this issue now but feel free to re-open if it's still not working.
